name: Dispatch Hello

on:
  workflow_dispatch:
    inputs:

      SAY_HELLO:
        default: true
        required: true
        type: boolean

      HELLO_RECIPIENT:
        default: world
        required: true
        type: string

jobs:

  hello:
    name: Say hello
    uses: ./.github/workflows/reusable.yml
    with:
      SAY_HELLO: ${{ inputs.SAY_HELLO }}
      HELLO_RECIPIENT: ${{ inputs.HELLO_RECIPIENT }}
