name: Testing Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:

      - name: Test Step
        run: |
          echo "hello world"
